apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: aad-developer-groups-monitor
  namespace: utvikleropplevelse
  labels:
    team: utvikleropplevelse
spec:
  image: {{ image }}
  port: 3000
  azure:
    application:
      enabled: true
      tenant: nav.no
  liveness:
    path: /
  readiness:
    path: /
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /metrics
  env:
    - name: MONITOR_HTTP_LISTEN_ADDRESS
      value: 0.0.0.0:3000
    - name: MONITOR_LOG_FORMAT
      value: json
    - name: MONITOR_LOG_LEVEL
      value: INFO
    - name: MONITOR_GROUP_IDS
      value: >-
        48120347-8582-4329-8673-7beb3ed6ca06,
        76e9ee7e-2cd1-4814-b199-6c0be007d7b4,
        eb5c5556-6c9a-4e54-83fc-f70cae25358d