apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: aad-developer-groups-monitor
  namespace: utvikleropplevelse
  labels:
    team: utvikleropplevelse
spec:
  image: {{ image }}
  port: 3000
  azure:
    application:
      enabled: true
      tenant: nav.no
  liveness:
    path: /
  readiness:
    path: /
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /metrics