name: Build and push
on: push
jobs:
  build:
    name: Build and push application image to GAR
    runs-on: ubuntu-22.04
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and push image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: utvikleropplevelse
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}