name: Build, push and deploy
on: push
jobs:
  build:
    name: Build and push application image to GAR
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and push image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: utvikleropplevelse
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy:
    if: github.ref == 'refs/heads/main'
    name: Deploy to prod-gcp
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy application to prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/app.yaml,.nais/alerts.yaml
          VAR: image=${{ needs.build.outputs.image }}