name: Build, push and deploy
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mise_task:
          - check:deadcode
          - check:golangci-lint
          - check:gosec
          - check:govet
          - check:govulncheck
          - check:staticcheck
          - ci:fmt
          - test
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # ratchet:jdx/mise-action@v4
      - run: mise run ${{ matrix.mise_task }}

  branch-protection-checkpoint:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - checks
    name: Branch protection checkpoint
    steps:
      - if: ${{ needs.checks.result != 'success' }}
        run: exit 1
      - run: echo "All checks and builds passed."

  build_and_push:
    if: github.ref == 'refs/heads/main'
    name: Build and push application image to GAR
    runs-on: ubuntu-latest
    needs:
      - branch-protection-checkpoint
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # ratchet:jdx/mise-action@v4
      - id: go-version
        run: echo "version=$(mise current go)" >> $GITHUB_OUTPUT
      - uses: nais/docker-build-push@751a312f0803eb96a05a41fadf51be19b7be362c # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: utvikleropplevelse
          build_args: GO_VERSION=${{ steps.go-version.outputs.version }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/app.yaml,.nais/alerts.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
