name: Build, push and deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and push application image to GAR
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v3
      - uses: asdf-vm/actions/install@v3
        with:
          before_install: |
            asdf install golang latest
            asdf global golang latest
      - run: make test
      - run: make check
      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: utvikleropplevelse
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
  deploy:
    name: Deploy to prod-gcp
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/app.yaml,.nais/alerts.yaml
          VAR: image=${{ needs.build.outputs.image }}